from typing import Iterator, List, Optional, Tuple, Union

class Map:
    def __init__(self, path: Union[str, bytes]) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> int: ...
    def __len__(self) -> int: ...
    def get(self, key: str, default: Optional[int] = None) -> Optional[int]: ...
    def keys(self) -> Iterator[str]: ...
    def values(self) -> Iterator[int]: ...
    def items(self) -> Iterator[Tuple[str, int]]: ...
    def search_re(self, regex: str) -> Iterator[Tuple[str, int]]: ...
    def search_lev(self, key: str, max_dist: int) -> Iterator[Tuple[str, int]]: ...

class MapBuilder:
    def __init__(self, path: Optional[str] = None) -> None: ...
    def insert(self, key: str, val: int) -> None: ...
    def finish(self) -> Optional[Map]: ...

class Set:
    def __init__(self, path: Union[str, bytes]) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def search_re(self, regex: str) -> Iterator[str]: ...
    def search_lev(self, key: str, max_dist: int) -> Iterator[str]: ...
    def is_disjoint(self, other: 'Set') -> bool: ...
    def is_subset(self, other: 'Set') -> bool: ...
    def is_superset(self, other: 'Set') -> bool: ...
    def union(self, other: 'Set') -> Iterator[str]: ...
    def intersection(self, other: 'Set') -> Iterator[str]: ...
    def difference(self, other: 'Set') -> Iterator[str]: ...
    def symmetric_difference(self, other: 'Set') -> Iterator[str]: ...

class SetBuilder:
    def __init__(self, path: Optional[str] = None) -> None: ...
    def insert(self, key: str) -> None: ...
    def finish(self) -> Optional[Set]: ...
